
server:
  port: 9080

spring:
  datasource:
    #url: jdbc:mysql://localhost:33088/mall_pms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:33088/test_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


logging:
  level:
    com.example.my.product: trace